### PR TITLE
Easier Uploading Functionality

### PR DESCRIPTION
**Pull request by xloem**

### CODE REVIEW

**Comment by AustEcon** [comment]
Thanks. I'll have to take a longer look at this. 

The plan I have in mind covers all of this functionality but I want to do it in a more modular way and with a more complete feature set for all things related to utxo splitting / utxo management (but I will need to finish up my work on bitsv this weekend + then also hook into the bip32 side of things...). 

I like what you're thinking though! 

Maybe we can work on something along these lines soon together so that it fulfills both of our needs and a broader range of applications in a way that will stand the test of time a bit better. (I need a couple of weeks though to iron out some other things... because I don't want to have to change around large parts of this library once (if) people start using it.

**Comment by xloem** [comment]
Sure.

It sounds like you'd like the interfaces to be more future proof, and to provide more control to the user than this.  Let me know if you have any more solid plans I could adjust to.

I think it's important to provide the community with a file upload tool.  I haven't found any others.

**Comment by AustEcon** [comment]
Yeah. I don't want to release the desktop GUI binaries etc. until I have a nice utxo splitting tab there with e.g. a nice overview / like a dashboard of the status of your utxo set...
In terms of larger uploads I think bip32 support will be needed to have 25 utxos for each of the child keys "locked and loaded" with a progress bar for "fresh/pure" (>=100kb) utxos that are pending confirmation... you get the idea... but all of this should be driven by lots of little, simple functions inside of the polyglot library (which in turn should extend bitsv and the bip32 extension I'm about to put out).
I have the little pieces in the works... just have to tie it all together... I'll get there... haha!

**Comment by AustEcon** [comment]
Continuing on with this here: https://github.com/AustEcon/polyglot/pull/18

**Pull request closed without merging**
