### PR TITLE
add a method to find confirmation count

### PR DESCRIPTION
**Pull request by xloem**
I I think I meant to submit this earlier, but missed it.  I haven't yet tested it with the new merges.

### CODE REVIEW

**Comment by AustEcon** [comment]
What's the usecase?

And using utxos as a proxy for what you really want (confirmation status of a tx) is an unreliable way to get it because what if you consumed the full utxo down to dust for that tx? Then there will be no utxo for it... 

More appropriate to directly request height of the txids via some API and work it out based on height of the tx and latest block tip height imo...

Anyway. I think this functionality is outside of scope. People can write their own code to do something like this imo.

**Comment by xloem** [comment]
Yeah I don't consume down to dust because I want the transaction to be required for including future transactions in case of a fork ...

Big transactions can sometimes be dropped before being confirmed, so I like to wait on them before assuming they went through.  I didn't think of the down-to-dust situation: I guess working more tightly with bitsv is important here.  Thanks for the feedback.

EDIT: would you consider adding a call to bitsv to confirm transactions before returning from uploads as a future improvement?

**Comment by AustEcon** [comment]
hmm... my initial gut feeling is that I don't want to impose any specific implementation for this kind of thing onto others. Would rather give the building blocks for them to make their own system for checking for confirmation status. Don't want to bloat the code that then needs to be maintained.

Are you thinking about it polling for it until it has reached some user-defined threshold?

**Comment by xloem** [comment]
That's how I was using it, yes.

**Comment by AustEcon** [comment]
I'll close this one sorry. Polling for block confirmations is a long-running, (blocking) process and I'd rather not deal with it.

**Pull request closed without merging**
